// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWJuj7owueK5aHLejXUU8ApvESSaAXez4',
    appId: '1:670053862489:web:aea4bd977ce25d24e23548',
    messagingSenderId: '670053862489',
    projectId: 'lyanna-bd625',
    authDomain: 'lyanna-bd625.firebaseapp.com',
    storageBucket: 'lyanna-bd625.appspot.com',
    measurementId: 'G-Z8M45NLHNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5prYy93zzFfRlDd7p5LkHthVLYxAoz2U',
    appId: '1:670053862489:android:b7562228fd63c3a9e23548',
    messagingSenderId: '670053862489',
    projectId: 'lyanna-bd625',
    storageBucket: 'lyanna-bd625.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgipj1MYcYgVgpwCpKj0Nsq4fBVua2AZk',
    appId: '1:670053862489:ios:0d8db23c1bf22f46e23548',
    messagingSenderId: '670053862489',
    projectId: 'lyanna-bd625',
    storageBucket: 'lyanna-bd625.appspot.com',
    androidClientId: '670053862489-n0mvnd36ohkda6nrib08bo75p0ml363r.apps.googleusercontent.com',
    iosClientId: '670053862489-16caekql213j81i17rheh36mcehrvpc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lyanna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgipj1MYcYgVgpwCpKj0Nsq4fBVua2AZk',
    appId: '1:670053862489:ios:8602315e39c38f1ce23548',
    messagingSenderId: '670053862489',
    projectId: 'lyanna-bd625',
    storageBucket: 'lyanna-bd625.appspot.com',
    androidClientId: '670053862489-n0mvnd36ohkda6nrib08bo75p0ml363r.apps.googleusercontent.com',
    iosClientId: '670053862489-149s671f35v6oabpd13ruqfjl1a9n8kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.lyanna.RunnerTests',
  );
}
